[project]
name = "odoo-addons-oca-pos"
version = "17.0.20231218.0"
dependencies = [
    "odoo-addon-pos_partner_birthdate>=17.0dev,<17.1dev",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 17.0",
]
